# Generated by Django 3.2.8 on 2021-10-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
